version: '3'

services:
  web_app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../src/web_app/frontend:/app/src/web_app/frontend
    environment:
      - FLASK_ENV=development

  simulator:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: python src/data_collection/simulator.py
    volumes:
      - ../src:/app/src
    environment:
      - API_URL=http://web_app:5000/data 